from random import Random
from typing import Optional


class PasswordGenerator:
    DEFAULT_LENGTH: int = ...
    DEFAULT_SEED: str = ...

    _SYMBOLS: str = ...
    _SPECIAL_SYMBOLS: str = ...

    def __init__(self,
                 *code_phrases: str,
                 length: Optional[int] = None,
                 seed: Optional[str] = None,
                 use_special_symbols: Optional[bool] = None):
        self._code_phrases: str = ...
        self._length: int = ...
        self._seed: str = ...
        self._use_special_symbols: bool = ...
        self._random: Random = ...

    @property
    def seed(self) -> str: ...

    @property
    def symbols(self) -> str: ...

    def generate(self) -> str: ...
